apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l2l-prd-rabbitmq
  namespace: l2l-prd
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azuredisk-premium-lrs
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2l-prd-rabbitmq
  namespace: l2l-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: l2l-prd-rabbitmq
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: l2l-prd-rabbitmq
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: l2l-prd-rabbitmq
        image: "rabbitmq:3.7.16-management"
        pullPolicy: IfNotPresent
        ports:
        - containerPort: 4369
          name: epmd
          protocol: TCP
        - containerPort: 5672
          name: amqp2
          protocol: TCP
        - containerPort: 15672
          name: api
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/rabbitmq"
          name: l2l-prd-rabbitmq
        env:
        - name: "RABBITMQ_DEFAULT_PASS"
          value: "91PwAv0zRm"
        - name: "RABBITMQ_DEFAULT_USER"
          value: "admin"
      volumes:
        - name: l2l-prd-rabbitmq
          persistentVolumeClaim:
            claimName: l2l-prd-rabbitmq
      hostname: l2l-prd-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: l2l-prd-rabbitmq
  namespace: l2l-prd
spec:
  ports:
  - port: 5672
  selector:
    app: l2l-prd-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: l2l-prd-rabbitmq-web
  namespace: l2l-prd
spec:
  ports:
  - port: 15672
  selector:
    app: l2l-prd-rabbitmq