apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: ingress-caas-prd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cloud@pixeon.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}