FROM registry.pixeon.cloud/korus:web.base
MAINTAINER yros.aguiar@pixeon.cloud


ARG APP_NAME=Web.SAC

SHELL ["powershell"]

COPY Web.SAC c:\\app\\Web.SAC
COPY *.xml  c:\\app/
COPY *.cfg  c:\\app/
COPY *.xsd  c:\\app/

RUN New-Website -Name 'Web.SAC' -Port 80 \
    -PhysicalPath 'c:\app\Web.SAC' -ApplicationPool '.NET v4.5'
EXPOSE 80

CMD Write-Host IIS Started... ; \
    while ($true) { Start-Sleep -Seconds 3600 }

