FROM registry.pixeon.cloud/korus:web.base
MAINTAINER yros.aguiar@pixeon.cloud


ARG APP_NAME=Web.Bussola

SHELL ["powershell"]

COPY Web.Bussola c:\\app\\Web.Bussola
COPY *.xml  c:\\app/
COPY *.cfg  c:\\app/
COPY *.xsd  c:\\app/

RUN New-Website -Name 'Web.Bussola' -Port 80 \
    -PhysicalPath 'c:\app\Web.Bussola' -ApplicationPool '.NET v4.5'
EXPOSE 80

CMD Write-Host IIS Started... ; \
    while ($true) { Start-Sleep -Seconds 3600 }

