version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    links:
      - "elasticsearch"
    ports:
      - "5601"
    labels:
      traefik.frontend.rule: Host:efk.dev.pixeon.cloud
      traefik.enable: 'true'
      traefik.backend: kibana-efk
      traefik.port: '8081'
      io.rancher.container.hostname_override: container_name
      traefik.frontend.headers.SSLProxyHeaders: X-Forwarded-Proto:https
      traefik.frontend.entryPoints: http,https
      traefik.frontend.headers.SSLRedirect: 'true'

  fluent-es:
    image: yunlzheng/fluent-es
    stdin_open: true
    links:
      - elasticsearch
    tty: true
    ports:
      - 24224:24224/tcp
    labels:
      io.rancher.scheduler.global: 'true'

