apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-integrador
  namespace: korus-apis-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-integrador
  template:
    metadata:
      labels:
        app: api-integrador
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: api-integrador
        image: "registry.pixeon.cloud/korus/api-integrador:dev-1.0.0.24"
        pullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: api-integrador
        env:
        - name: PCPF
          value: https://korus-pessoa.pixeon.cloud/api/{0}/PessoaFisica/BuscarPorCPF;
---
apiVersion: v1
kind: Service
metadata:
  name: api-integrador
  namespace: korus-apis-prd
spec:
  ports:
  - port: 80
  selector:
    app: api-integrador