apiVersion: v1
kind: Secret
metadata:
  name: korus-apis-secret
  namespace: korus-apis-prd
data:
  auth: 'c3Vwb3J0ZS1wcm9kOiRhcHIxJDBibXhFY1AvJGNyYVFrblR0ei5SZTJpRm15bzBpcjAK' #htpasswd -c ./auth suporte-prod --> cat auth | base64
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: korus-apis-prd-ingress
  namespace: korus-apis-prd
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: korus-apis-secret
    nginx.ingress.kubernetes.io/auth-type: basic
spec:
  tls:
  - hosts:
    - korus-convenios.pixeon.cloud
    - korus-exame.pixeon.cloud
    - korus-exame-faturamento.pixeon.cloud
    - korus-exame-matriz.pixeon.cloud
    - korus-medicos.pixeon.cloud
    - korus-origem.pixeon.cloud
    - korus-pessoa.pixeon.cloud
    - korus-planos.pixeon.cloud
    - korus-unidades.pixeon.cloud
    - korus-integrador.pixeon.cloud
    secretName: korus-apis-prd-secret
  rules:
  - host: korus-convenios.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-convenios
          servicePort: 80
  - host: korus-exame.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-exame
          servicePort: 80
  - host: korus-exame-faturamento.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-exame-faturamento
          servicePort: 80
  - host: korus-exame-matriz.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-matriz
          servicePort: 80
  - host: korus-medicos.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-medicos
          servicePort: 80
  - host: korus-origem.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-origem
          servicePort: 80
  - host: korus-pessoa.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-pessoa
          servicePort: 80
  - host: korus-planos.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-planos
          servicePort: 80
  - host: korus-unidades.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-unidades
          servicePort: 80
  - host: korus-integrador.pixeon.cloud
    http:
      paths:
      - backend:
          serviceName: api-integrador
          servicePort: 80