apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agfakorus-dev-rabbitmq
  namespace: agfakorus-dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azuredisk-premium-lrs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agfakorus-dev-rabbitmq
  namespace: agfakorus-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agfakorus-dev-rabbitmq
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: agfakorus-dev-rabbitmq
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: agfakorus-dev-rabbitmq
        image: "registry.pixeon.cloud/rabbitmq-delayed-message:3.7.8-management"
        pullPolicy: IfNotPresent
        ports:
        - containerPort: 4369
          name: epmd
          protocol: TCP
        - containerPort: 5672
          name: amqp2
          protocol: TCP
        - containerPort: 15672
          name: api
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/rabbitmq"
          name: agfakorus-dev-rabbitmq
        env:
        - name: "RABBITMQ_DEFAULT_PASS"
          value: "04Kisq3bMwLy9zGj"
        - name: "RABBITMQ_DEFAULT_USER"
          value: "agfadevrabbit"
      volumes:
        - name: agfakorus-dev-rabbitmq
          persistentVolumeClaim:
            claimName: agfakorus-dev-rabbitmq
      hostname: agfakorus-dev-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: agfakorus-dev-rabbitmq
  namespace: agfakorus-dev
spec:
  ports:
  - port: 5672
  selector:
    app: agfakorus-dev-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: agfakorus-dev-rabbitmq-web
  namespace: agfakorus-dev
spec:
  ports:
  - port: 15672
  selector:
    app: agfakorus-dev-rabbitmq