apiVersion: apps/v1
kind: Deployment
metadata:
  name: agfakorus-prd-api-agfa-documentos
  namespace: agfakorus-prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agfakorus-prd-api-agfa-documentos
  template:
    metadata:
      labels:
        app: agfakorus-prd-api-agfa-documentos
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: agfakorus-prd-api-agfa-documentos
        image: "registry.pixeon.cloud/korus/api-agfa-documentos:latest"
        ports:
        - containerPort: 80
          name: agfa-prd-apidoc
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        - name: "ASPNETCORE_URLS"
          value: "http://agfakorus-prd-api-agfa-documentos"
        - name: "Services__Atendimento"
          value: "http://agfakorus-prd-api-atendimento/api/"
        - name: "Services__Authentication"
          value: "http://agfakorus-prd-api-autenticacao/api/"
        - name: "Services__AwsS3__accessAccessKeyID"
          value: "AKIAIDHKLHK6DM5JY67Q"
        - name: "Services__AwsS3__bucketName"
          value: "suite-net"
        - name: "Services__AwsS3__secretAccessKey"
          value: "yLHAj05XjH/F+tGbkt5/vPuHov8p3wg+koPcnfGn"
---
apiVersion: v1
kind: Service
metadata:
  name: agfakorus-prd-api-agfa-documentos
  namespace: agfakorus-prd
spec:
  ports:
  - port: 80
  selector:
    app: agfakorus-prd-api-agfa-documentos