version: '2'
services:
  metabase:
    image: metabase/metabase:latest
    links:
        - postgres
    ports:
        - "3000"
    environment:
        - MB_DB_TYPE=postgres
        - MB_DB_DBNAME=metabase
        - MB_DB_PORT=5432
        - MB_DB_USER=metabase
        - MB_DB_PASS=K888r7HjyzboUlJy
        - MB_DB_HOST=postgres
  postgres:
    image: postgres:9.6
    ports:
        - "5432"
    environment:
        - POSTGRES_PASSWORD=K888r7HjyzboUlJy
        - POSTGRES_DB=metabase
        - POSTGRES_USER=metabase
    volumes:
        - pgdata:/var/lib/postgresql/data
    labels:
        traefik.frontend.rule: Host:data.pixeon.cloud
        traefik.enable: 'true'
        traefik.backend: data
        traefik.port: '3000'
        io.rancher.container.hostname_override: container_name
        traefik.frontend.headers.SSLProxyHeaders: X-Forwarded-Proto:https
        traefik.frontend.entryPoints: http,https
        traefik.frontend.headers.SSLRedirect: 'true'

volumes: 
  pgdata: